name: Node Project
on:
  push:
    branches:
      - master
jobs:
  build-node-deploy:
    runs-on: ubuntu-latest # 我们选择使用最新的ubuntu系统
    steps:
    - name: Checkout
      uses: actions/checkout@master # 将代码拷贝到虚机中
      with:
        persist-credentials: false
    - name: Install
      run: |
        npm install
    - name: Node
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 使用刚新建的secret
        BRANCH: gh-pages # 存放产物的分支名称
        FOLDER: dist  # 存放build后产物的目录  
        BUILD_SCRIPT: npm install && node app.js # 执行的命令
